# Generated by Django 3.0.4 on 2021-05-31 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='create',
        ),
    ]
